// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl3fewIu5yPKi4KJmXJCPkTYhM_5mJp2s',
    appId: '1:462751561014:web:75209164ecc9a7ee59ef97',
    messagingSenderId: '462751561014',
    projectId: 'medisum-87afb',
    authDomain: 'medisum-87afb.firebaseapp.com',
    storageBucket: 'medisum-87afb.appspot.com',
    measurementId: 'G-6DY7YPB833',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3bukqkl9eQswnNMLhN6XKAegzYgQkT58',
    appId: '1:462751561014:android:42a7bccb22582a6a59ef97',
    messagingSenderId: '462751561014',
    projectId: 'medisum-87afb',
    storageBucket: 'medisum-87afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_L1OwfwWI97vOsK52NqesLH_DmRYeU6c',
    appId: '1:462751561014:ios:ab01efcd19bd918c59ef97',
    messagingSenderId: '462751561014',
    projectId: 'medisum-87afb',
    storageBucket: 'medisum-87afb.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_L1OwfwWI97vOsK52NqesLH_DmRYeU6c',
    appId: '1:462751561014:ios:ab01efcd19bd918c59ef97',
    messagingSenderId: '462751561014',
    projectId: 'medisum-87afb',
    storageBucket: 'medisum-87afb.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl3fewIu5yPKi4KJmXJCPkTYhM_5mJp2s',
    appId: '1:462751561014:web:87328428e36b2bab59ef97',
    messagingSenderId: '462751561014',
    projectId: 'medisum-87afb',
    authDomain: 'medisum-87afb.firebaseapp.com',
    storageBucket: 'medisum-87afb.appspot.com',
    measurementId: 'G-GS6096LEX0',
  );
}
